version: '3.4'

services:

  almundo-db:
    image: postgres:11-alpine
    container_name: almundo-db
    environment:
      - POSTGRES_DB=almundo-db
      - POSTGRES_USER=adminalmundo
      - POSTGRES_PASSWORD=almundoadmin
    ports:
      - 5432:5432
    networks:
      - almundo-net

  almundo-front:
    image: angular:latest
    container_name: almundo-front
    working_dir: /front
    volumes:
      - ../front:/front
    build:
      context: ../front
      dockerfile: Dockerfile.development
    ports:
      - 4200:4200
    tty: true
    networks:
      - almundo-net
    command: ng serve --host 0.0.0.0 --disable-host-check

  almundo-back:
    image: node:12.14.1-alpine
    container_name: almundo-back
    working_dir: /back
    volumes:
      - ../back:/back
    build:
      context: ../back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    networks:
      - almundo-net
    links:
      - almundo-db
    depends_on: [almundo-db]
    command: npm run start-dev
  
  almundo-nginx:
    image: nginx:alpine
    container_name: almundo-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - almundo-back
      - almundo-front
    links:
      - almundo-front:front
      - almundo-back:back
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - almundo-net

networks:
  almundo-net:
    driver: bridge
