version: '3.4'

services:
  # almundo-db:
  #   image: postgres:11-alpine
  #   container_name: almundo-db
  #   environment:
  #     - POSTGRES_DB=almundo-db
  #     - POSTGRES_USER=adminalmundo
  #     - POSTGRES_PASSWORD=almundoadmin
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - almundo-net

  # almundo-back:
  #   image: node:12.14.1-alpine
  #   container_name: almundo-back
  #   volumes:
  #     - ../back:/back
  #   build:
  #     context: ../back
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on: [almundo-db]
  #   networks:
  #     - almundo-net
  #   links:
  #     - almundo-db
  
  almundo-nginx:
    container_name: almundo-static
    build:
      context: ../front
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - almundo-back
    # links:
    #   - almundo-back:back
    # command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
    networks:
      - almundo-net

networks: 
  almundo-net:
    driver: bridge
